### ISSUE TITLE
Reference to missing security.md

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/covid-alert-documentation#24]
The vulnerability disclosure policy mentions a security.md file. This file is not present in this repository.

**Comment by davidbgk** [comment]
I can reproduce, I see two options: either linking to the [Security policy tab](https://github.com/cds-snc/covid-alert-documentation/security/policy) of this repository or referencing [the source itself](https://github.com/cds-snc/.github/blob/master/SECURITY.md).

**Comment by obrien-j** [comment]
Just cloned content from the vdp into the security.md, not seeing a clever way to symlink. Should be sufficient for now unless other thoughts?

**Comment by AntoineAugusti** [comment]
Sounds good @obrien-j

**Comment by sboots** [comment]
(Added to the [Vulnerability Disclosure Policy](https://github.com/cds-snc/covid-alert-documentation/blob/main/VulnerabilityDisclosurePolicy.md); closing this issue. Thanks @davidbgk @AntoineAugusti !) 🙌
