### ISSUE TITLE
Bug | Bogue

### ISSUE THREAD

**Issue by LeadSongDog** [cds-snc/covid-alert-documentation#34]
# Summary | Résumé
Reduce minimumExposureDurationMinutes 

> One paragraph explanation of the bug, including why it is a problem (i.e. what does it prevent a user from doing or accomplishing). Screenshots are greatly helpful here too.

New variants of concern are known to propagate through briefer generations (as little as 24 hours) and on shorter contacts. Please consider reducing minimumExposureDurationMinutes from the existing arbitrary value of 15.

**Comment by obrien-j** [comment]
Hey @LeadSongDog , apologies for the shuffling. In keeping with our newly really release #31 practices, I've moved this up into the covid-alert-documentation repo as our central point for taking input from folks outside the team, and am converting the issue into a Discussion.
