### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by iplayfast** [cds-snc/covid-alert-documentation#9]
Your readme.md is very detailed in what is used to build it, how to build it, who built it and so on. 
The one thing that it's lacking (because developers are always self absorbed in their project) is an explanation of what it does, why you built it, what it accomplishes.

For example it's one thing to say it tracks who you've been near who as covid-19, but it also says (according to https://digital.canada.ca/2020/07/31/continuously-improving-covid-alert/?fbclid=IwAR2C2zh9Nl1OltFEATlQP9asNN7cANd2akhwbfm5uM37buyUX9GN2Kx9CeQ )  it doesn't use gps, or track your location.

To me the two ideas conflict. Perhaps you can explain, as this app on the surface appears to be a big invasion of privacy how it's not an invasion of privacy and how (in general) it works.

**Comment by obrien-j** [comment]
@iplayfast Did you want to take a crack at a more descriptive title, or would you mind if I did? 

It'll help make it more identifiable while triaging through the issues list.

**Comment by obrien-j** [comment]
Closing due to the lack of activity in the absence of a stalebot to do it for me. I've open up the discussions tab in line with #31 so feel free to pose any questions/ideas over there if you still have any outstanding
